title: DocyDocs
description: This is a description.
theme: just-the-docs

url: https://docynoah.github.io/docs/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
